### ISSUE TITLE
Persistent upload button even after multiple reloads

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#112]
Simple steps to reproduce the caching bug @krishnasrinivas

- build the current master from minio and start the minio server and login
- now logout, npm run release build a new asset file.
- copy the new assets and build again.
- make sure to not close the window from your chrome, let it stay at the login screen.
- now login you will see the "update" icon.
- click twice, thrice the window loads but it doesn't go away.

Current code always reloads from cache - https://files.gitter.im/minio/minio/ma93/Screen-Shot-2016-02-24-at-2.15.37-AM.png

https://files.gitter.im/minio/minio/7E3N/CachingAffect.mov

Thanks to @pankajdoharey for pointing me to right direction to use location.reload(true)

**Comment by klausenbusk** [comment]
The correct way to fix it is to change the filename every-time we update css/js.
So something like:
```
/minio/functions.MINIO_UI_VERSION.js
/minio/index_bundle.MINIO_UI_VERSION.js
```
Dunno if we need it for {jquery,bootstrap}.min.js, also we should add `max-age=31536000` (1 year) or maybe just 1 month??

**Comment by harshavardhana** [comment]
> The correct way to fix it is to change the filename every-time we update css/js.
> So something like:
> 
> /minio/functions.MINIO_UI_VERSION.js
> /minio/index_bundle.MINIO_UI_VERSION.js
> Dunno if we need it for {jquery,bootstrap}.min.js, also we should add something like max-age=31536000 (1 year).
> BTW: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching is worth reading, regards cache.

Yes this is spot on. Currently react does this by adding `?<uniqueid>` perhaps that really doesn't help.

**Comment by harshavardhana** [comment]
This is fixed.
