### ISSUE TITLE
progress: Abort and Continue texts have more padding and are not centered.

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#123]
![screen shot 2016-03-02 at 5 13 38 pm](https://cloud.githubusercontent.com/assets/622699/13481396/3585fb28-e09a-11e5-8f6b-fe5922aeb3e5.png)

**Comment by rushenn** [comment]
@harshavardhana  This is not the right fix. It occurred due to the missing font classes. Please check my fix 89e766f

**Comment by harshavardhana** [comment]
> @harshavardhana This occurred due to the missing font classes. Please check my fix 89e766f

Ah cool.
