### ISSUE TITLE
How to delete files and buckets?

### ISSUE THREAD

**Issue by nodesocket** [minio/miniobrowser#154]
I might be missing it, but how do you delete files and buckets in the web interface?

**Comment by harshavardhana** [comment]
> I might be missing it, but how do you delete files and buckets in the web interface?

We deliberately did not add as a safety mechanism so that users don't accidentally delete a whole bunch of files - usually a common possibility. 

If you still wish to delete files and buckets you can use - https://github.com/minio/mc , has a handy command line tool.

**Comment by nodesocket** [comment]
Ok makes sense, but I feel deleting could be done just on files in the browser list. When you click delete, pop open a modal with a confirmation. I would think that would be enough of a verification.

I'd really like to see deleting of files implemented in the web interface.

**Comment by harshavardhana** [comment]
> Ok makes sense, but I feel deleting could be done just on files in the browser list. When you click delete, pop open a modal with a confirmation. I would think that would be enough of a verification.
> 
> I'd really like to see deleting of files implemented in the web interface.

We will discuss internally on how safely this can be implemented.

**Comment by harshavardhana** [comment]
Fixed by

https://github.com/minio/miniobrowser/pull/194

and 

https://github.com/minio/miniobrowser/pull/195

**Comment by nodesocket** [comment]
Is this already pushed lived? I'm not seeing the option to delete files and buckets?

**Comment by GarimaKapoor** [comment]
@nodesocket, The issue is fixed and will come with the next release.

**Comment by jGielen** [comment]
@harshavardhana, is the part of deleting buckets already handled in the web interface?

**Comment by nodesocket** [comment]
When is the next release? I just tried today **1/13/17** and still no way to delete buckets and files.
