### ISSUE TITLE
Public buckets

### ISSUE THREAD

**Issue by nodesocket** [minio/miniobrowser#156]
**Feature request:** The ability to mark a bucket "public" and expose a http link to all files.

For example:

- I create a **public** bucket named "vacation".
For every file I upload into that bucket, it can be publically accessed via `http://127.0.0.1:9000/vacation/file-name-here.jpg`.

Considerations:

- Getting all the `mime-types` and http response headers right.
- Should it really run on a same port as minio `9000`? Perhaps it has a separate port for isolation.

**Comment by harshavardhana** [comment]
This is part of the roadmap.

**Comment by harshavardhana** [comment]
Closing this in favor of https://github.com/minio/minio/issues/2816 - bucket policy has been implemented already.
