### ISSUE TITLE
should give better error when no bucket is selected on upload

### ISSUE THREAD

**Issue by brendanashworth** [minio/miniobrowser#184]
When you log into a fresh server in the browser with no buckets, it'll show you an empty Browse page, with no buckets selected. If you try to upload a file, it'll either give you the error `Bucket name invalid:` (note no bucket name) or `Error occurred uploading '..file..'`. This isn't immediately clear that no buckets exist / you don't have a bucket selected.

Example:
![screen shot 2016-08-26 at 2 49 24 pm](https://cloud.githubusercontent.com/assets/3038254/18021453/518432d0-6b9c-11e6-9eb9-6bd86c42a07e.png)

**Comment by harshavardhana** [comment]
:+1:

**Comment by harshavardhana** [comment]
// cc @vadmeste

**Comment by vadmeste** [comment]
This seems to be already fixed.

![screenshot from 2016-11-12 17-24-55](https://cloud.githubusercontent.com/assets/283197/20239277/3fa54bbe-a8fd-11e6-83a5-6bbde94ae471.png)

**Comment by harshavardhana** [comment]
Closing as fixed in master.
