### ISSUE TITLE
'Change password' modal needs to show tooltips for buttons.

### ISSUE THREAD

**Issue by balamurugana** [minio/miniobrowser#203]

**Comment by rushenn** [comment]
There is a tooltip for 'generate key' button. I think we don't tooltip for other generic buttons as the icons are straightforward.

**Comment by harshavardhana** [comment]
> There is a tooltip for 'generate key' button. I think we don't tooltip for other generic buttons as the icons are straightforward.

It was deemed confusing so we have to add tooltips for them as well.

**Comment by rushenn** [comment]
Okay, will do.
