### ISSUE TITLE
Incorrect MIME type set for images

### ISSUE THREAD

**Issue by rushenn** [minio/miniobrowser#204]
![screen shot 2016-10-01 at 12 30 01](https://cloud.githubusercontent.com/assets/13393018/19012419/2ab5ec4a-87d3-11e6-9ca2-1d0b8c4f8542.png)

![1](https://cloud.githubusercontent.com/assets/13393018/19012433/5fc856de-87d3-11e6-84d9-46a80c52526c.jpg)

This has to be data-type="image"

**Comment by harshavardhana** [comment]
// cc @vadmeste

**Comment by vadmeste** [comment]
Fixes were sent to minio/minio to address this issue. However I still have another working patch which uses javascript mime library to identify the content type based on the object name. Now, Meta in FS will be always enabled, so it seems that content-type will be always sent by Minio server and my patch will be useless in that case. 

Am I right? What do you think ?

**Comment by harshavardhana** [comment]
@vadmeste I think it is a good idea to have a fallback . If content type is not known by the server.

**Comment by harshavardhana** [comment]
Fixed by #232
