### ISSUE TITLE
share-object box should horizontal scroll bar

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/miniobrowser#206]
![share-object](https://cloud.githubusercontent.com/assets/634494/19023162/dd771688-8904-11e6-9897-2d7e97d7bd2c.png)

* The input box in the middle should have horizontal scroll bar.

* share and delete buttons should have tool tips

**Comment by rushenn** [comment]
It's a text field, can't have a visible scroll bar. It'll be corrected once we implement the copy to clipboard feature.

**Comment by rushenn** [comment]
Working on overall UI code cleaning, will push the changes tomorrow.

![screen shot 2016-10-03 at 01 05 01](https://cloud.githubusercontent.com/assets/13393018/19023205/fb5c8a10-8905-11e6-81c2-b95ebab0be72.png)

**Comment by krishnasrinivas** [comment]
@rushenn ok cool, also pull in https://github.com/minio/miniobrowser/pull/207 ... this is what was causing problems that day.

**Comment by rushenn** [comment]
Oh, will do.

**Comment by harshavardhana** [comment]
Is this fixed @krishnasrinivas @rushenn ?

**Comment by rushenn** [comment]
yes, it's fixed.
