### ISSUE TITLE
Need to update credentials change result message

### ISSUE THREAD

**Issue by donatello** [minio/miniobrowser#215]
After https://github.com/minio/minio/pull/2929 is merged to master, in the response to the `SetAuth` jsonrpc call, a new item is added (in case of successful rpc call):

```
// SetAuthReply - reply for SetAuth
type SetAuthReply struct {
    Token       string   `json:"token"`
    UIVersion   string   `json:"uiVersion"`
    PeerErrMsgs []string `json:"peerErrMsgs"`
}
```

The new PeerErrMsgs array of strings tells about any error messages while updating credentials on each Minio server in the cluster. If this array is non-empty, the user needs to be notified with these messages, so they can take action to manually fix the servers.

**Comment by donatello** [comment]
Also, in case of (jsonrpc) error response, the error message may now be really large, as it may include strings built using `PeerErrMsgs` - so a UI change to display this properly may be needed.

**Comment by harshavardhana** [comment]
@donatello what needs to be done here?

**Comment by donatello** [comment]
So based on https://github.com/minio/minio/blob/master/cmd/web-handlers.go#L365-L439 `webAPIHandlers.SetAuth`, we need to:

1. In case of errors on other servers, but success on the server connected to the browser, no error is returned in JSON RPC response, but the reply parameter, has errors in the `PeerErrMsgs` property - this needs to be notified to the user.
2. In case of error on server connected to browser and error on other servers, the error response has `"ALERT: We gave up due to: '%s', but there were more errors. Please check the server logs."`, and this can be shown to the user - but maybe the error message will be long, so appearance in the browser may need to be improved.
3. In case of error on server connected to browser, and no errors on other servers, the error response has the required message and can be displayed without any change.
4. No change in UI in case of success.

**Comment by harshavardhana** [comment]
Can you take this up @donatello ?

**Comment by harshavardhana** [comment]
Closing this as stale for now.. We will re-open when we discuss about these messages in detail.
