### ISSUE TITLE
Avoid positioning bucket name position and used/free space position so close to avoid user confusion

### ISSUE THREAD

**Issue by vadmeste** [minio/miniobrowser#216]
Having used/free space below bucket name can confuse the user and let him think that each bucket owns its own disk space

![browser](https://cloud.githubusercontent.com/assets/283197/19496464/80b9e9a2-957f-11e6-985e-db6cabad00bd.png)

Need to wait until time comes to make UI enhancements

**Comment by harshavardhana** [comment]
Can you explain more about the confusion here? and also propose a solution.

**Comment by vadmeste** [comment]
@harshavardhana, my suggestion is to move disk status (free/total space) either below Minio Browser logo or above the bucket name, also we probably need to add some design to emphasis the difference of context between disk status and bucket + objects.

Why? I just think that with the current layout, newcomers will directly think that disk status is associated to the bucket and not to the whole Minio server.

**Comment by harshavardhana** [comment]
> @harshavardhana, my suggestion is to move disk status (free/total space) either below Minio Browser logo or above the bucket name, also we probably need to add some design to emphasis the difference of context between disk status and bucket + objects.

We had this argument before, but the UI didn't fit or look well with the changes proposed. Once we have quota support this will fit in properly. So what we have right now is correct . There hasn't been any community reports on this so we can revisit it.

**Comment by vadmeste** [comment]
> We had this argument before, but the UI didn't fit or look well with the changes proposed. Once we have quota support this will fit in properly. So what we have right now is correct . There hasn't been any community reports on this so we can revisit we can close this for now.

:+1:
