### ISSUE TITLE
Implement share slider for expiry time and also a box to take custom date field 

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#219]
![browser-bug-1](https://cloud.githubusercontent.com/assets/622699/19585310/474b9d3c-9700-11e6-8527-a050de1f7979.png)

**Comment by rushenn** [comment]
@harshavardhana Can you give me an idea about share slider.

**Comment by harshavardhana** [comment]
> @harshavardhana Can you give me an idea about share slider.

Will do @rushenn

**Comment by harshavardhana** [comment]
ping @rushenn - lets talk about this when you have time.

**Comment by harshavardhana** [comment]
ping @rushenn

**Comment by harshavardhana** [comment]
Fixed by #247
