### ISSUE TITLE
Bucket creation failure message could be better

### ISSUE THREAD

**Issue by justinclift** [minio/miniobrowser#224]
Trying out Minio as a newbie, the failure message when creating a bucket with capital letters in it could be improved:
![screen shot 2016-10-22 at 02 39 41](https://cloud.githubusercontent.com/assets/406299/19615997/df40abfe-9800-11e6-805f-c3784f7fa1f8.png)
It's not immediately obvious why the bucket name isn't valid.

Is it feasible to maybe have some feedback in the entry field, as the name is being typed?

That way when an invalid character is typed, a warning could be shown or something (then cleared when the char is backspaced).

That would be a strong way to guide people to using only valid names. :smile:

**Comment by harshavardhana** [comment]
Thanks @justinclift sure we will address this.

**Comment by justinclift** [comment]
Cool. :smile:

Unsure if useful, but two ways to address it pop into mind right away:

* Easiest approach → "Bucket name invalid: [name]&lt;br />[Only lowercase letters, full stops, and numbers allowed](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules)"
* More interactive approach → When an invalid character is typed in the field, the entry area could turn from orange to red, and **just above it** the "[Only lowercase letters, full stops, and numbers allowed](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules)" guidance would be shown (eg where the user is already looking).  Similar for if the user gives a full stop as the first character (with message suitable to that)

That's just ideas, there are likely tonnes of ways to get this done. :smile:

**Comment by harshavardhana** [comment]
This is fixed by https://github.com/minio/minio/issues/3296
