### ISSUE TITLE
minio browser > settings > read-only display access/secret key says 'change password'

### ISSUE THREAD

**Issue by charudut** [minio/miniobrowser#234]
steps to reproduce the defect:
1) go to minio browser - https://play.minio.io:9000
2) top-right dropdown button
3) click settings
4) popup says 'change password` while the access/secret keys are read-only

**Comment by harshavardhana** [comment]
Yes this is a feature play.minio.io:9000 is a public server one is not allowed to change password,  if its set by the environment variable. using MINIO_ACCESS_KEY, MINIO_SECRET_KEY.

**Comment by charudut** [comment]
ok, thanks for the quick reply! appreciate it.
