### ISSUE TITLE
Policy modal can be more intuitive

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/miniobrowser#235]
Current Policy modal is not intuitive when you want to share an entire bucket:

![policy](https://cloud.githubusercontent.com/assets/634494/20381200/63d0380a-accc-11e6-8bed-1360f12609f4.png)

Can be like: (ignore the alignment issue)
![policy2](https://cloud.githubusercontent.com/assets/634494/20381393/49a71c2c-accd-11e6-8b8a-9c4bb834b3b5.png)

Also "Object name" place holder should be "Prefix"

**Comment by harshavardhana** [comment]
> Can be like: (ignore the alignment issue)
> 
> 
> Also "Object name" place holder should be "Prefix"

The decision was to use 

"Bucket Policy (BucketName)" 

Prefill "Object Name" with "*"

**Comment by harshavardhana** [comment]
Closing this as it was decided to keep the current style, we will re-open when we have another set of discussion on this.
