### ISSUE TITLE
share link text box should be horizontally scrollable

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/miniobrowser#236]
![share](https://cloud.githubusercontent.com/assets/634494/20381438/78011c9e-accd-11e6-8ab5-4644aff8f10d.png)

the text box should be horizontally scrollable, else it looks a little weird.

**Comment by rushenn** [comment]
@krishnasrinivas It's a text field and can't have any visible scrollbars. With features like click to select and copy to clipboard already available, I think there is no need to alter the text fields to have any scrollbars.

**Comment by krishnasrinivas** [comment]
@rushenn let's check with ab/harsha

**Comment by rushenn** [comment]
@krishnasrinivas 👍

**Comment by harshavardhana** [comment]
Actually this was decided to be not done, priority is to provide the slider bar for selecting the shareable link. https://github.com/minio/miniobrowser/issues/219
