### ISSUE TITLE
List level loading stats are not visible

### ISSUE THREAD

**Issue by rushenn** [minio/miniobrowser#238]
Loading indicator for bucket and object list are no longer visible.

**Comment by harshavardhana** [comment]
> Loading indicator for bucket and object list are no longer visible.

what is this issue?

**Comment by rushenn** [comment]
@harshavardhana There was a loading spinner if there is delay in listing objects. It's not visible right now. Should be a CSS issue, I will look into it.

**Comment by harshavardhana** [comment]
> @harshavardhana There was a loading spinner if there is delay in listing objects. It's not visible right now. Should be a CSS issue, I will look into it.

It is visible for me if you build it through minio server UI.  are you doing a local dev setup ?

**Comment by rushenn** [comment]
I'm checking the https://play.minio.io:9000/. Can you see it here?

**Comment by harshavardhana** [comment]
Yes I do on the login page.

**Comment by rushenn** [comment]
Not the main page loader. There is another tiny spinner which should display on each bucket/object listing. When you click any bucket list in sidebar, if there is a delay on retrieving objects, the spinner should popup and replace the bucket icon (drive icon). 

![1](https://cloud.githubusercontent.com/assets/13393018/20457711/e5c58694-aeb6-11e6-9e3f-20b707d4e70e.jpg)

This should be CSS issue.

**Comment by harshavardhana** [comment]
ping @rushenn

**Comment by rushenn** [comment]
@harshavardhana https://github.com/minio/miniobrowser/pull/253
