### ISSUE TITLE
Not easy to click on '...' button when we have many objects in the list 

### ISSUE THREAD

**Issue by vadmeste** [minio/miniobrowser#251]
(+) button is above the ... button of the last object element in the objects list. Little difficult to click on ... button

![screenshot from 2016-12-04 20-04-06](https://cloud.githubusercontent.com/assets/283197/20868469/d7734c1e-ba5c-11e6-8b17-16df559bd94b.png)

**Comment by rushenn** [comment]
@vadmeste I'll find a way to fix this

**Comment by harshavardhana** [comment]
Fixed by #252
