### ISSUE TITLE
Enable contrast on the dashboard

### ISSUE THREAD

**Issue by alexellis** [minio/miniobrowser#255]
The dashboard is a mixture of light blue and gray on pure white. It would be much easier to read if you could harden up the colour.

**Comment by rushenn** [comment]
@alexellis We have worked on file type icons and adjusted the text contrast level. These changes are yet to be implemented. Any feedback would be greatly appreciated.

![minio-browser](https://cloud.githubusercontent.com/assets/13393018/22011839/10aff53c-dcb7-11e6-8737-c93fd42792ba.png)

**Before/after previews**
![browser-before-after](https://cloud.githubusercontent.com/assets/13393018/22012145/aafd0228-dcb8-11e6-97bf-0a30d586428f.jpg)

**Comment by alexellis** [comment]
Hi, I replied to this via DM with @rushenn
