### ISSUE TITLE
Does miniobrowwer call minio server through the s3 api ?

### ISSUE THREAD

**Issue by yanyixing** [minio/miniobrowser#256]
Does miniobrowwer call minio server through the s3 api ?

**Comment by krishnasrinivas** [comment]
@yanyixing no, we use our own JSON-RPC for miniobrowser to minio-server communication.

**Comment by yanyixing** [comment]
So, miniobrowser can't be used for other S3 compatible storage?

**Comment by harshavardhana** [comment]
> So, miniobrowser can't be used for other S3 compatible storage?

@yanyixing no it cannot be.  miniobrowser is not a standalone product.

**Comment by krishnasrinivas** [comment]
no, minio-browser started initially with the idea that it can just use s3-apis. But it was limiting that we could not do things like showing storage info, changing of access/secret key etc (management operations)

**Comment by yanyixing** [comment]
@krishnasrinivas , Can I use minio-browser manage my amazon s3 storage? Just like show files ,upload files and delete files

**Comment by krishnasrinivas** [comment]
no, because minio-browser does not use s3 api. But instead you can use https://github.com/minio/mc CLI interface or if you want a UI you can use https://cyberduck.io/
