### ISSUE TITLE
copy to clipboard

### ISSUE THREAD

**Issue by dcharbonnier** [minio/miniobrowser#258]
Chrome 55 / mac
When I clic on _copy to clipboard_ the `http://` part of the url is not in the clipboard

**Comment by harshavardhana** [comment]
> When I clic on copy to clipboard the http:// part of the url is not in the clipboard

This is fixed by https://github.com/minio/miniobrowser/commit/b37b7f8f280bd434241fd4463436f69f55bfe81f
