### ISSUE TITLE
Unexpected EOF on uploading large file, not sure what went wrong the file is in-tact. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#27]
```ERRO[0109] CreateObject failed.                          Error={Cause:unexpected EOF Type:*errors.errorString CallTrace:[{Line:246 Filename:pkg/fs/fs-object.go Function:fs.Filesystem.CreateObject Env:map[]} {Line:182 Filename:object-handlers.go Function:main.CloudStorageAPI.PutObjectHandler Env:map[]}] SysInfo:map[host.cpus:8 mem.total:24MB mem.heap.total:19MB host.os:linux host.name:ip-172-31-15-108 host.lang:go1.5.3 host.arch:amd64 mem.used:9.4MB mem.heap.used:9.4MB]}```

**Comment by harshavardhana** [comment]
File present on server v/s 
```
md5sum distrikt_2014-01-31T07_31_11-08_00.mp3
9e99a84ac116469ff43b9be0a2360a88  distrikt_2014-01-31T07_31_11-08_00.mp3
```
```
md5 ~/Downloads/distrikt_2014-01-31T07_31_11-08_00.mp3
MD5 (/Users/harsha/Downloads/distrikt_2014-01-31T07_31_11-08_00.mp3) = 9e99a84ac116469ff43b9be0a2360a88
```

**Comment by harshavardhana** [comment]
Not a bug perhaps a server side issue where a presigned PUT is not really handled properly.

**Comment by krishnasrinivas** [comment]
looks like a server side issue, is it reproducible?

**Comment by harshavardhana** [comment]
> looks like a server side issue, is it reproducible?

Yes perhaps with presigned put operation.

**Comment by harshavardhana** [comment]
This issue is expected upon cancelling the upload, it is not a bug. Closing.
