### ISSUE TITLE
Settings do not work

### ISSUE THREAD

**Issue by dswd** [minio/miniobrowser#270]
In the latest version (2017-01-25) clicking the "Settings" menu item just reloads the page but does not show the settings. That worked in the previous version.

**Comment by krishnasrinivas** [comment]
@dswd works for me on Chrome version 55.
@rushenn mentioned that it is not working for him as well, @rushenn can you post your observations? what browser are you using?

**Comment by rushenn** [comment]
@krishnasrinivas I've tested on Chrome 55 and latest Firefox. Modals are not working for me.

**Comment by krishnasrinivas** [comment]
I see the bug, sorry I was looking at the wrong place.
