### ISSUE TITLE
browser: unexpected behavior on pressing back button  

### ISSUE THREAD

**Issue by koolhead17** [minio/miniobrowser#48]
I am using Chrome to play with minio-browser & i have noticed this issue while previewing an uploaded a pdf file.

Way to reproduce the bug:

1. Add a pdf file as object to a bucket
2. Once uploaded open it in browser.
3. While it is still opening/loading press back button

The screenshot is the output you will get on the browser, i refreshed it 4-5 times. 

![screenshot 2016-02-04 01 09 29](https://cloud.githubusercontent.com/assets/41746/12794924/88eeb764-cadd-11e5-9975-82d36d2accb4.png)

**Comment by harshavardhana** [comment]
@koolhead17 - can you reproduce this with new release?

**Comment by koolhead17** [comment]
Closing this, since we are no more opening anything inside browser. It gets downloaded.
