### ISSUE TITLE
ui: Test for browser compatibility and fix it

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/miniobrowser#72]
Test for browser compatibility with:

- Chrome
- Firefox
- Safari
- IE10

**Comment by harshavardhana** [comment]
> IE10

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign - is not supported on IE any versions.

**Comment by harshavardhana** [comment]
We can leverage - https://github.com/paulmillr/es6-shim

**Comment by krishnasrinivas** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign - is not supported on IE any versions.

Object.assign will actually be transpiled by babel

**Comment by harshavardhana** [comment]
> Object.assign will actually be transpiled by babel

This is the error i see let me paste it.. 

![screen shot 2016-02-08 at 8 45 01 pm](https://cloud.githubusercontent.com/assets/622699/12907827/dcfd9576-cea4-11e5-91de-0eda4e496bcf.png)

**Comment by krishnasrinivas** [comment]
Ah, OK, looks like I have to import babel-polyfill: http://babeljs.io/docs/learn-es2015/

**Comment by krishnasrinivas** [comment]
http://babeljs.io/docs/usage/polyfill/

**Comment by Gouthamve** [comment]
It doesn't work on Safari :( This is built from github source yesterday.

<img width="1278" alt="screen shot 2016-02-20 at 5 00 08 pm" src="https://cloud.githubusercontent.com/assets/7354143/13196444/9bdacc0a-d7f3-11e5-845d-a996e79ff472.png">

**Comment by harshavardhana** [comment]
> It doesn't work on Safari :( This is built from github source yesterday.

Was able to reproduce this as well.

**Comment by harshavardhana** [comment]
Closing not reproducible on safari anymore, will re-open if seen again.
