### ISSUE TITLE
ui: alert should have an 'expand' option, which provides more details.

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/miniobrowser#83]

**Comment by harshavardhana** [comment]
![screen shot 2016-02-10 at 2 24 20 am](https://cloud.githubusercontent.com/assets/622699/12944680/8fcdf012-cf9d-11e5-8859-07d08a646980.png)

**Comment by harshavardhana** [comment]
We have standardize these messages, keeping it here so that we remember to fix these.

**Comment by harshavardhana** [comment]
> We have standardize these messages, keeping it here so that we remember to fix these.

Currently "show more" doesn't display anything just reloads the page.

**Comment by harshavardhana** [comment]
Nothing to do here.. closing.
