### ISSUE TITLE
ui: Right side dropdown is slightly off in padding on current master

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#89]
Browser used is - Chrome Version 48.0.2564.103 (64-bit)

![screen shot 2016-02-09 at 2 20 05 pm](https://cloud.githubusercontent.com/assets/622699/12932667/a4ae0d10-cf38-11e5-9036-6eb25b4b9083.png)

**Comment by rushenn** [comment]
I think this commit is not merged.  https://github.com/rushenn/me/commit/8064415afee9716bc0f0e4e8804a1987162f464d

Can't see any changes in holodeck.

**Comment by harshavardhana** [comment]
> I think this commit is not merged. rushenn@8064415
> 
> Can't see any changes in holodeck.

Once merged the changes have been to rebuilt for them to be reflected.  You won't see merge commits here reflecting on holodeck.
