### ISSUE TITLE
scroll: Odd transitions and differences while scrolling Chrome OSX.

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#95]
Scrolling with mouse not hovering on the scroll bar.

![scroll_1](https://cloud.githubusercontent.com/assets/622699/12990381/f9c708e2-d0be-11e5-9d5d-b3191ee1e9aa.png)

Scrolling with mouse hovering on the scroll bar. 
![scolling_2](https://cloud.githubusercontent.com/assets/622699/12990418/2c36592c-d0bf-11e5-8825-ea49ff3643d3.png)

Want to know if this is expected behavior.

**Comment by rushenn** [comment]
It's look like the native OSX scrollbar. I think for whatever reason, custom scrollbar is failing to render. Will check.

**Comment by harshavardhana** [comment]
Not reproducible anymore, closing.
